name: Release Brave Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 20 * * 0-6"
  workflow_dispatch:
    inputs:
      channel:
        description: 'Brave channel to build (stable, beta, nightly)'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - beta
          - nightly
      flavor:
        description: 'Brave flavor (browser, origin)'
        required: true
        default: 'browser'
        type: choice
        options:
          - browser
          - origin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: build
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        chmod a+x ./brave-builder.sh
        # Pass channel and flavor. If triggered by cron, default to stable browser.
        FLAVOR=${{ github.event.inputs.flavor || 'browser' }}
        CHANNEL=${{ github.event.inputs.channel || 'stable' }}
        ./brave-builder.sh $CHANNEL $FLAVOR
        mkdir dist
        mv *AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: Brave-AppImages
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: Brave-AppImages

        # Snapshot Release
        - name: get date
          run: |
            SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
            echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
          continue-on-error: false
        - name: create snapshot
          uses: softprops/action-gh-release@v2
          with:
            name: "Snapshot ${{ env.SNAPSHOT_TAG}}"
            tag_name: "${{ env.SNAPSHOT_TAG}}"
            prerelease: false
            draft: false
            generate_release_notes: false
            make_latest: false
            files: |
              *.AppImage*
          continue-on-error: false

        # Continuous releases
        - name: release stable
          uses: marvinpinto/action-automatic-releases@latest
          if: contains(github.event.inputs.channel, 'stable') || github.event_name == 'schedule'
          with:
            title: Continuous Stable
            automatic_release_tag: continuous-stable
            prerelease: false
            draft: false
            files: |
              *stable*.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}

        - name: release beta
          uses: marvinpinto/action-automatic-releases@latest
          if: github.event.inputs.channel == 'beta'
          with:
            title: Continuous Beta
            automatic_release_tag: continuous-beta
            prerelease: true
            draft: false
            files: |
              *beta*.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}

        - name: release nightly
          uses: marvinpinto/action-automatic-releases@latest
          if: github.event.inputs.channel == 'nightly'
          with:
            title: Continuous Nightly
            automatic_release_tag: continuous-nightly
            prerelease: true
            draft: false
            files: |
              *nightly*.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}

